# Generated by Django 2.0.6 on 2018-09-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180905_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
