# Generated by Django 2.0.6 on 2018-08-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='formaat',
            field=models.CharField(choices=[('X', 'Kies formaat'), ('L', 'Groot'), ('M', 'Medium'), ('S', 'Klein')], default='X', max_length=1),
        ),
        migrations.AddField(
            model_name='product',
            name='oriëntatie',
            field=models.CharField(choices=[('X', 'Kies oriëntatie'), ('L', 'Liggend'), ('S', 'Staand'), ('V', 'Vierkant')], default='X', max_length=1),
        ),
        migrations.AddField(
            model_name='product',
            name='prijs',
            field=models.CharField(choices=[('X', 'Kies prijs'), ('M', '500 tot 3000 euro'), ('H', 'Vanaf 3000 euro'), ('B', 'Tot 499 euro')], default='X', max_length=1),
        ),
        migrations.AddField(
            model_name='product',
            name='prijstype',
            field=models.CharField(choices=[('X', 'Kies prijstype'), ('B', 'Koop en Huur'), ('K', 'Koop'), ('H', 'Huur')], default='X', max_length=1),
        ),
        migrations.AddField(
            model_name='product',
            name='stijl',
            field=models.CharField(choices=[('X', 'Kies jouw kunststijl'), ('R', 'Realistisch'), ('I', 'Imprestionistisch'), ('A', 'Abstract'), ('E', 'Expressionistisch')], default='X', max_length=1),
        ),
        migrations.AddField(
            model_name='product',
            name='techniek',
            field=models.CharField(choices=[('X', 'Kies techniek'), ('S', 'Sculptuur'), ('F', 'Fotografie'), ('D', 'Doek'), ('P', 'Papier')], default='X', max_length=1),
        ),
    ]
