# Generated by Django 2.0.6 on 2018-08-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180828_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='kunstenaar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
