# Generated by Django 2.0.6 on 2018-08-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_kunstenaar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='formaat',
            field=models.CharField(choices=[('X', 'Kies formaat'), ('G', 'Groot'), ('M', 'Medium'), ('K', 'Klein')], default='X', max_length=1),
        ),
    ]
