# Generated by Django 2.0.6 on 2018-08-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20180830_0803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='Enter Description')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='lijst',
            field=models.CharField(choices=[('L', 'Is met lijst'), ('Z', 'Is zonder lijst')], default='X', max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='oriëntatie',
            field=models.CharField(choices=[('X', 'Kies oriëntatie'), ('L', 'Liggend'), ('S', 'Staand'), ('V', 'Vierkant'), ('D', 'Driedimensionaal')], default='X', max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='prijs',
            field=models.CharField(choices=[('X', 'Kies prijs'), ('B', 'Tot 499 euro'), ('M', '500 tot 999 euro'), ('H', '1000 to 2999 euro'), ('L', '3000 euro en hoger')], default='X', max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='techniek',
            field=models.CharField(choices=[('X', 'Kies techniek'), ('S', 'Sculptuur'), ('F', 'Fotografie'), ('D', 'Doek, Paneel'), ('P', 'Papier'), ('G', 'Grafiek'), ('D', 'Digitale techniek'), ('O', 'Overig')], default='X', max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='thema',
            field=models.CharField(choices=[('X', 'Kies jouw thema'), ('A', 'Architectuur'), ('D', 'Dieren'), ('E', 'Eten en Drinken'), ('L', 'Landschap en Natuur'), ('C', 'Cultuur en Land'), ('M', 'Mens en Portret'), ('O', 'Overig')], default='X', max_length=1),
        ),
    ]
