# Generated by Django 2.0.6 on 2018-08-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20180830_0931'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pictures',
        ),
        migrations.AlterField(
            model_name='product',
            name='lijst',
            field=models.CharField(choices=[('L', 'Ja'), ('Z', 'Nee')], default='X', max_length=1),
        ),
    ]
