# Generated by Django 2.0.6 on 2018-08-31 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20180831_0626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Width_of_object_in_CM',
            new_name='WidthCM',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='length_of_object_in_CM',
            new_name='lengthCM',
        ),
    ]
