# Generated by Django 2.0.6 on 2018-09-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='formaat',
            field=models.CharField(choices=[('X', 'Kies formaat'), ('G', 'Groot'), ('M', 'Normaal'), ('K', 'Klein')], default='X', max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='prijstype',
            field=models.CharField(choices=[('X', 'Kies een prijstype'), ('B', 'Geen voorkeur'), ('K', 'Koop'), ('H', 'Huur')], default='X', max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='stijl',
            field=models.CharField(choices=[('X', 'Kies jouw kunststijl'), ('R', 'Realistisch'), ('I', 'Impresionistisch'), ('G', 'Gestileerd'), ('A', 'Abstract')], default='X', max_length=1),
        ),
    ]
